version: '3'
services:
  app:
    build: .
    container_name: "aplicacao"
    command: ["go", "run", "main.go"]
    ports:
      - "8090:8090"
    restart: unless-stopped
    depends_on:
      - db
  
  db:
    build:
      context: ./banco_dados
      dockerfile: Dockerfile
    container_name: "basedados"
    environment:
      - POSTGRES_DB=neoway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@P0st123
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  db-data: